name: Minha Primeira Pipeline
#QUANDO É ATIVADA (EM UM PUSH NA MAIN)
on: 
    push:
        branches: 
            - main
#QUAIS AÇÕES SÃO REALIZADAS
jobs:

    #Testando o código antes do deploy
    teste:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm test
            


    #Subindo nosso código no Github Pages
    deploy:
        needs: teste
        runs-on: ubuntu-latest
        steps:
            - run: echo "REALIZANDO O DEPLOY"