name: Minha Primeira Pipeline
#QUANDO É ATIVADA (EM UM PUSH NA MAIN)
on: 
    push:
        branches: 
            - main
#QUAIS AÇÕES SÃO REALIZADAS
jobs:

    #Testando o código antes do deploy
    teste:
        runs-on: ubuntu-latest
        steps:
            - run: echo "REALIZANDO TESTE!"
            


    #Subindo nosso código no Github Pages
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo "REALIZANDO O DEPLOY"