name: Minha Primeira Pipeline
#QUANDO É ATIVADA (EM UM PUSH NA MAIN)
on: 
    push:
        branches: 
            - main
#QUAIS AÇÕES SÃO REALIZADAS
jobs:

    #Testando o código antes do deploy
    teste:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm test
            


    #Subindo nosso código no Github Pages
    deploy:
        permissions: 
            contents: write
        needs: teste
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: git fetch 
            - run: git config --global user.email "carloswgama@gmail.com"
            - run: git config --global user.name "Carlos W. Gama"
            - run: git checkout -B gh-pages
            - run: git merge main
            - run: git push --force origin gh-pages
            